language: smalltalk
sudo: false

os:
- linux

install:
- pip install --user benchupload


smalltalk:
- Pharo-7.0

script:
- $SMALLTALK_CI_HOME/run.sh

after_success:
 - find /home/travis -name "*.xml"
 - python -mbenchupload

after_failure:
 - python -mbenchupload
