Class {
	#name : #'GCP_GCFSDocumentTransform_FieldTransform_ServerValue',
	#superclass : #PBTypeEnum,
	#classVars : [
		'REQUEST_TIME',
		'SERVER_VALUE_UNSPECIFIED'
	],
	#category : #'Google-Firestore-Definitions'
}

{ #category : #'as yet unclassified' }
GCP_GCFSDocumentTransform_FieldTransform_ServerValue class >> REQUEST_TIME [
	^ REQUEST_TIME
]

{ #category : #'as yet unclassified' }
GCP_GCFSDocumentTransform_FieldTransform_ServerValue class >> SERVER_VALUE_UNSPECIFIED [
	^ SERVER_VALUE_UNSPECIFIED
]

{ #category : #'as yet unclassified' }
GCP_GCFSDocumentTransform_FieldTransform_ServerValue class >> initialize [
SERVER_VALUE_UNSPECIFIED := 0.
REQUEST_TIME := 1.

]
