Class {
	#name : #'GPBFieldDescriptorProto_Type',
	#superclass : #PBTypeEnum,
	#classVars : [
		'TYPE_BOOL',
		'TYPE_BYTES',
		'TYPE_DOUBLE',
		'TYPE_ENUM',
		'TYPE_FIXED32',
		'TYPE_FIXED64',
		'TYPE_FLOAT',
		'TYPE_GROUP',
		'TYPE_INT32',
		'TYPE_INT64',
		'TYPE_MESSAGE',
		'TYPE_SFIXED32',
		'TYPE_SFIXED64',
		'TYPE_SINT32',
		'TYPE_SINT64',
		'TYPE_STRING',
		'TYPE_UINT32',
		'TYPE_UINT64'
	],
	#category : #'Protobuf-Definitions'
}

{ #category : #'as yet unclassified' }
GPBFieldDescriptorProto_Type class >> TYPE_BOOL [
	^ TYPE_BOOL
]

{ #category : #'as yet unclassified' }
GPBFieldDescriptorProto_Type class >> TYPE_BYTES [
	^ TYPE_BYTES
]

{ #category : #'as yet unclassified' }
GPBFieldDescriptorProto_Type class >> TYPE_DOUBLE [
	^ TYPE_DOUBLE
]

{ #category : #'as yet unclassified' }
GPBFieldDescriptorProto_Type class >> TYPE_ENUM [
	^ TYPE_ENUM
]

{ #category : #'as yet unclassified' }
GPBFieldDescriptorProto_Type class >> TYPE_FIXED32 [
	^ TYPE_FIXED32
]

{ #category : #'as yet unclassified' }
GPBFieldDescriptorProto_Type class >> TYPE_FIXED64 [
	^ TYPE_FIXED64
]

{ #category : #'as yet unclassified' }
GPBFieldDescriptorProto_Type class >> TYPE_FLOAT [
	^ TYPE_FLOAT
]

{ #category : #'as yet unclassified' }
GPBFieldDescriptorProto_Type class >> TYPE_GROUP [
	^ TYPE_GROUP
]

{ #category : #'as yet unclassified' }
GPBFieldDescriptorProto_Type class >> TYPE_INT32 [
	^ TYPE_INT32
]

{ #category : #'as yet unclassified' }
GPBFieldDescriptorProto_Type class >> TYPE_INT64 [
	^ TYPE_INT64
]

{ #category : #'as yet unclassified' }
GPBFieldDescriptorProto_Type class >> TYPE_MESSAGE [
	^ TYPE_MESSAGE
]

{ #category : #'as yet unclassified' }
GPBFieldDescriptorProto_Type class >> TYPE_SFIXED32 [
	^ TYPE_SFIXED32
]

{ #category : #'as yet unclassified' }
GPBFieldDescriptorProto_Type class >> TYPE_SFIXED64 [
	^ TYPE_SFIXED64
]

{ #category : #'as yet unclassified' }
GPBFieldDescriptorProto_Type class >> TYPE_SINT32 [
	^ TYPE_SINT32
]

{ #category : #'as yet unclassified' }
GPBFieldDescriptorProto_Type class >> TYPE_SINT64 [
	^ TYPE_SINT64
]

{ #category : #'as yet unclassified' }
GPBFieldDescriptorProto_Type class >> TYPE_STRING [
	^ TYPE_STRING
]

{ #category : #'as yet unclassified' }
GPBFieldDescriptorProto_Type class >> TYPE_UINT32 [
	^ TYPE_UINT32
]

{ #category : #'as yet unclassified' }
GPBFieldDescriptorProto_Type class >> TYPE_UINT64 [
	^ TYPE_UINT64
]

{ #category : #'as yet unclassified' }
GPBFieldDescriptorProto_Type class >> initialize [
TYPE_DOUBLE := 1.
TYPE_FLOAT := 2.
TYPE_INT64 := 3.
TYPE_UINT64 := 4.
TYPE_INT32 := 5.
TYPE_FIXED64 := 6.
TYPE_FIXED32 := 7.
TYPE_BOOL := 8.
TYPE_STRING := 9.
TYPE_GROUP := 10.
TYPE_MESSAGE := 11.
TYPE_BYTES := 12.
TYPE_UINT32 := 13.
TYPE_ENUM := 14.
TYPE_SFIXED32 := 15.
TYPE_SFIXED64 := 16.
TYPE_SINT32 := 17.
TYPE_SINT64 := 18.

]
