Class {
	#name : #'GPBGeneratedCodeInfo_Annotation',
	#superclass : #PBTypeMessage,
	#instVars : [
		'#path => ((PBPropertySlot with: #PBTypeInt32) fieldName: \'path\'; fieldNumber: 1; beRepeated; jsonFieldName: \'path\')',
		'#source_file => ((PBPropertySlot with: #PBTypeString) fieldName: \'source_file\'; fieldNumber: 2; beOptional; jsonFieldName: \'sourceFile\')',
		'#begin => ((PBPropertySlot with: #PBTypeInt32) fieldName: \'begin\'; fieldNumber: 3; beOptional; jsonFieldName: \'begin\')',
		'#end => ((PBPropertySlot with: #PBTypeInt32) fieldName: \'end\'; fieldNumber: 4; beOptional; jsonFieldName: \'end\')'
	],
	#category : #'Protobuf-Definitions'
}
