Class {
	#name : #'GPBUninterpretedOption_NamePart',
	#superclass : #PBTypeMessage,
	#instVars : [
		'#name_part => ((PBPropertySlot with: #PBTypeString) fieldName: \'name_part\'; fieldNumber: 1; jsonFieldName: \'namePart\')',
		'#is_extension => ((PBPropertySlot with: #PBTypeBool) fieldName: \'is_extension\'; fieldNumber: 2; jsonFieldName: \'isExtension\')'
	],
	#category : #'Protobuf-Definitions'
}
